services:
  server:
    build:
      context: ./singadrive-web-server
      dockerfile: ./Dockerfile  
    ports:
      - '5000:5000'
    volumes:
      - ./singadrive-web-server:/app
    environment:
      POSTGRES_DB: singadrive_db
      POSTGRES_USER: ${SINGADRIVE_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${SINGADRIVE_POSTGRES_PASSWORD}
      MONGODB_DB: singadrive_db
    network_mode: host

  client:
    build:
      context: ./singadrive-web-client
      dockerfile: ./Dockerfile 
    ports:
      - '3000:3000'
    volumes:
      - ./singadrive-web-client:/app
    network_mode: host
