services:
  server:
    build:
      context: ./melon-server
      dockerfile: ./Dockerfile  
    ports:
      - '5000:5000'
    volumes:
      - ./melon-server:/app
    environment:
      POSTGRES_DB: melon_brain_db
      POSTGRES_USER: ${MELON_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${MELON_POSTGRES_PASSWORD}
      MONGODB_DB: melon_brain_db
    network_mode: host

  client:
    build:
      context: ./melon-client
      dockerfile: ./Dockerfile 
    ports:
      - '3000:3000'
    volumes:
      - ./melon-client:/app
    network_mode: host

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    network_mode: host

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: melon_brain_db
      POSTGRES_USER: ${MELON_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${MELON_POSTGRES_PASSWORD}
    command: postgres -c listen_addresses=*
    network_mode: host

  flyway:
    network_mode: host
    image: flyway/flyway:latest
    command:
      - "-url=jdbc:postgresql://localhost:5432/melon_brain_db"
      - "-user=${MELON_POSTGRES_USERNAME}"
      - "-password=${MELON_POSTGRES_PASSWORD}"
      - "migrate"
    volumes:
      - ./postgreSQL-migrations:/flyway/sql

  pgadmin:
    network_mode: host
    image: dpage/pgadmin4
    ports:
      - '8080:8080'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mongo_volume
