services:
  server:
    build:
      context: ./singadrive-web-server
      dockerfile: ./Dockerfile  
    ports:
      - '5000:5000'
    network_mode: host
    environment:
      CHOKIDAR_USEPOLLING: true
      POSTGRES_DB: singadrive_db
      POSTGRES_USER: ${SINGADRIVE_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${SINGADRIVE_POSTGRES_PASSWORD}
      MONGODB_DB: singadrive_db
    volumes:
      - "./singadrive-web-server:/app"